//
// Generated file, do not edit! Created by opp_msgc 4.4 from package/data/data.msg.
//

#ifndef _DATA_M_H_
#define _DATA_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0404
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


namespace wsn_energy {

/**
 * Class generated from <tt>package/data/data.msg</tt> by opp_msgc.
 * <pre>
 * packet Data{
 *     double time;  		
 *     
 *     int destinationPort; 	  
 *     int destinationIPAddress; 
 *     
 * 	string value; 		
 * }
 * </pre>
 */
class Data : public ::cPacket
{
  protected:
    double time_var;
    int destinationPort_var;
    int destinationIPAddress_var;
    opp_string value_var;

  private:
    void copy(const Data& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Data&);

  public:
    Data(const char *name=NULL, int kind=0);
    Data(const Data& other);
    virtual ~Data();
    Data& operator=(const Data& other);
    virtual Data *dup() const {return new Data(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getTime() const;
    virtual void setTime(double time);
    virtual int getDestinationPort() const;
    virtual void setDestinationPort(int destinationPort);
    virtual int getDestinationIPAddress() const;
    virtual void setDestinationIPAddress(int destinationIPAddress);
    virtual const char * getValue() const;
    virtual void setValue(const char * value);
};

inline void doPacking(cCommBuffer *b, Data& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Data& obj) {obj.parsimUnpack(b);}

}; // end namespace wsn_energy

#endif // _DATA_M_H_
